//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arxius.UserIntreface.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arxius.UserIntreface.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie nieudane.
        /// </summary>
        internal static string MessageLoginFailed {
            get {
                return ResourceManager.GetString("MessageLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsgEmptySchedule.
        /// </summary>
        internal static string MsgEmptySchedule {
            get {
                return ResourceManager.GetString("MsgEmptySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsgEnrollment.
        /// </summary>
        internal static string MsgEnrollment {
            get {
                return ResourceManager.GetString("MsgEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsgFileError.
        /// </summary>
        internal static string MsgFileError {
            get {
                return ResourceManager.GetString("MsgFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsgHowToLogin.
        /// </summary>
        internal static string MsgHowToLogin {
            get {
                return ResourceManager.GetString("MsgHowToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsgLoginFailed.
        /// </summary>
        internal static string MsgLoginFailed {
            get {
                return ResourceManager.GetString("MsgLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsgNetworkError.
        /// </summary>
        internal static string MsgNetworkError {
            get {
                return ResourceManager.GetString("MsgNetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsgSave.
        /// </summary>
        internal static string MsgSave {
            get {
                return ResourceManager.GetString("MsgSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły kursu.
        /// </summary>
        internal static string PageNameCourseDetails {
            get {
                return ResourceManager.GetString("PageNameCourseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista kursów.
        /// </summary>
        internal static string PageNameCoursesList {
            get {
                return ResourceManager.GetString("PageNameCoursesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminarz.
        /// </summary>
        internal static string PageNameDates {
            get {
                return ResourceManager.GetString("PageNameDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punkty ECTS.
        /// </summary>
        internal static string PageNameEcts {
            get {
                return ResourceManager.GetString("PageNameEcts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista pracowników.
        /// </summary>
        internal static string PageNameEmployeesList {
            get {
                return ResourceManager.GetString("PageNameEmployeesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona logowania.
        /// </summary>
        internal static string PageNameLogin {
            get {
                return ResourceManager.GetString("PageNameLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona główna.
        /// </summary>
        internal static string PageNameMain {
            get {
                return ResourceManager.GetString("PageNameMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualności.
        /// </summary>
        internal static string PageNameNewsFeed {
            get {
                return ResourceManager.GetString("PageNameNewsFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan zajęć offline.
        /// </summary>
        internal static string PageNameOfflineSchedule {
            get {
                return ResourceManager.GetString("PageNameOfflineSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan zajęć.
        /// </summary>
        internal static string PageNameSchedule {
            get {
                return ResourceManager.GetString("PageNameSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista studentów.
        /// </summary>
        internal static string PageNameStudentsList {
            get {
                return ResourceManager.GetString("PageNameStudentsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil użytkownika.
        /// </summary>
        internal static string PageNameUserProfile {
            get {
                return ResourceManager.GetString("PageNameUserProfile", resourceCulture);
            }
        }
    }
}
