//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arxius.Services.PCL.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Regex {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Regex() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arxius.Services.PCL.Properties.Regex", typeof(Regex).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sala:(.*?)&lt;\/span.
        /// </summary>
        internal static string RegexForCourseClassroom {
            get {
                return ResourceManager.GetString("RegexForCourseClassroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to courseDetails(.*?)&lt;\/tr&gt;.
        /// </summary>
        internal static string RegexForCourseDetails {
            get {
                return ResourceManager.GetString("RegexForCourseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ects(.*)&lt;\/td&gt;.
        /// </summary>
        internal static string RegexForCourseEcts {
            get {
                return ResourceManager.GetString("RegexForCourseEcts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to courseHeader(.*?)&lt;\/tr&gt;.
        /// </summary>
        internal static string RegexForCourseHeader {
            get {
                return ResourceManager.GetString("RegexForCourseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href(.*)&gt;(.*?)&lt;\/a&gt;.
        /// </summary>
        internal static string RegexForCourseName {
            get {
                return ResourceManager.GetString("RegexForCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to term(.*?)&lt;\/span.
        /// </summary>
        internal static string RegexForCourseTime {
            get {
                return ResourceManager.GetString("RegexForCourseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type(.*?)&lt;\/span.
        /// </summary>
        internal static string RegexForCourseType {
            get {
                return ResourceManager.GetString("RegexForCourseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;(.*?)&lt;\/li&gt;.
        /// </summary>
        internal static string RegexForListElement {
            get {
                return ResourceManager.GetString("RegexForListElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tbody&gt;(.*)&lt;\/tbody&gt;.
        /// </summary>
        internal static string RegexForTableBody {
            get {
                return ResourceManager.GetString("RegexForTableBody", resourceCulture);
            }
        }
    }
}
